### ISSUE TITLE
no help with missing .net components

### ISSUE THREAD

**Issue by GoogleCodeExporter** [eyal0/mergetorrent#1]
```
When trying to run the 1.1 exe on a Win2000 system, the error "Contact your
app publisher for missing .Net framework (v2.0.50727)" is given.
I see no help in the program, nor in the documentation with locating and
installing the missing components.
```

Original issue reported on code.google.com by `goo...@polyglotinc.com` on 14 May 2010 at 6:06

**Comment by GoogleCodeExporter** [comment]
```
as a follow-up, I have tracked down .Net 2.0 framework install, installed it, 
and had
Microsoft Auto update download and install all known updates,
BUT, I still get the error "Missing Method Exception" when attempting to browse 
for
an input file.  The exception text is....

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.MissingMethodException: Method not found: 'Void
System.Windows.Forms.FileDialog.set_AutoUpgradeEnabled(Boolean)'.
   at mergetorrent.MainForm.FindTorent_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32
clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr
wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase: file:///C:/WINNT/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
mergetorrent
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase:
file:///C:/Documents%20and%20Settings/Administrator/My%20Documents/My%20Download
s/mergetorrent-v1.1.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 8.0.0.0
    Win32 Version: 8.0.50727.42 (RTM.050727-4200)
    CodeBase:
file:///C:/WINNT/assembly/GAC_MSIL/Microsoft.VisualBasic/8.0.0.0__b03f5f7f11d50a
3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINNT/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINNT/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e08
9/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINNT/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/Syst
em.Drawing.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.50727.832 (QFE.050727-8300)
    CodeBase:
file:///C:/WINNT/assembly/GAC_MSIL/System.Runtime.Remoting/2.0.0.0__b77a5c561934
e089/System.Runtime.Remoting.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

Original comment by `goo...@polyglotinc.com` on 14 May 2010 at 7:23

**Comment by GoogleCodeExporter** [comment]
```
I don't know.  .Net 2.0 is the absolute minimum that you could be using, 
however. 
Consider downloading .Net Framework 4.0.  It's the latest from Microsoft and it 
was
released in April.

http://msdn.microsoft.com/en-us/netframework/default.aspx

Let me know if that helps.
```

Original comment by `shawarma...@gmail.com` on 15 May 2010 at 12:41
- Changed state: **Started**

**Comment by GoogleCodeExporter** [comment]
```
Unfortunately, everything newer than .Net 2.0 seems to require at least WinXP 
(and I
am on Win2K).
After I kept launching the windows update web site and downloading/installing 
every
update in their database (took about 5 iterations before it said no more left),
I now no longer get the error message above when I launch the input file 
browser.
```

Original comment by `goo...@polyglotinc.com` on 16 May 2010 at 12:47

**Comment by GoogleCodeExporter** [comment]
```
Updating Windows solved the issue.
```

Original comment by `shawarma...@gmail.com` on 16 May 2010 at 3:47
- Changed state: **Invalid**
- Added labels: **OpSys-Windows**
